name: Deploy to Firebase(Development)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Firebase CLI
        run: yarn global add firebase-tools

      - name: Install dependencies
        run: yarn install

      - name: Deploy to Development
        environment:
          name: Development
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > serviceAccountKey.json
          yarn build
          export GOOGLE_APPLICATION_CREDENTIALS=serviceAccountKey.json
          firebase use pomodoro-adventure-dev
          firebase deploy --only functions
